language: android
android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    - build-tools-25.0.1
    - android-25

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21
    - addon-google_apis-google-25

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-addon-google_apis-google-25
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
env:
  - _FORCE_LOGS=1 TEST=unit ANDROID_AVD=test TARGET=android-21 ABI=armeabi-v7a
  - _FORCE_LOGS=1 TEST=functional PLATFORM_VERSION=5.0.2 ANDROID_AVD=test TARGET=android-21 ABI=armeabi-v7a
  - _FORCE_LOGS=1 TEST=functional PLATFORM_VERSION=7.1.1 ANDROID_AVD=test TARGET=android-25 ABI=google_apis/armeabi-v7a
before_install:
  - echo y | android update sdk --no-ui --all --filter android-25,sys-img-armeabi-v7a-google_apis-25
before_script:
  # node stuff
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  - nvm install 6
  - npm install -g gulp
  - npm install -g mocha
  - npm install
  - node --version
  - npm --version

  # android stuff
  - android list targets
  - echo no | android create avd --force -n test -t $TARGET --abi $ABI
  # - emulator -avd test -no-audio -no-window &
  - adb devices
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  # - adb wait-for-device
  - adb devices
  - adb shell input keyevent 82 &
script:
  - android list targets
  - gulp eslint && DEVICE=android mocha -t 900000 -R spec build/test/$TEST
after_success:
  - gulp coveralls
